/** Specific local-class exports; css-modules.spec.ts checks the real compiler table. */
declare module '*skin-center.module.css' {
  const classes: {
    readonly actions: string
    readonly backgroundHead: string
    readonly backgroundHint: string
    readonly backgroundHintMuted: string
    readonly backgroundLabel: string
    readonly backgroundRange: string
    readonly backgroundRow: string
    readonly backgroundValue: string
    readonly badge: string
    readonly badgeActive: string
    readonly badgeTrying: string
    readonly button: string
    readonly buttonGhost: string
    readonly buttonPrimary: string
    readonly card: string
    readonly cardBody: string
    readonly cardDescription: string
    readonly cardHead: string
    readonly cardHeaderStatic: string
    readonly cardName: string
    readonly cardTagline: string
    readonly enableHint: string
    readonly enableLabel: string
    readonly enableRow: string
    readonly error: string
    readonly head: string
    readonly headText: string
    readonly intro: string
    readonly list: string
    readonly offNote: string
    readonly pluginCard: string
    readonly pluginName: string
    readonly sectionList: string
    readonly swatch: string
    readonly switch: string
    readonly switchOn: string
    readonly switchThumb: string
    readonly themeButton: string
    readonly themeButtonActive: string
    readonly themeLabel: string
    readonly themeRow: string
    readonly titleBadge: string
    readonly wallpaperActions: string
    readonly wallpaperCard: string
    readonly wallpaperControls: string
    readonly wallpaperDir: string
    readonly wallpaperDirAdd: string
    readonly wallpaperDirInput: string
    readonly wallpaperDirPath: string
    readonly wallpaperDirRemove: string
    readonly wallpaperDirs: string
    readonly wallpaperGrid: string
    readonly wallpaperName: string
    readonly wallpaperSection: string
    readonly wallpaperStatus: string
    readonly wallpaperStatusError: string
    readonly wallpaperThumb: string
    readonly wallpaperThumbEmpty: string
    readonly wallpaperThumbWrap: string
    readonly wallpaperType: string
  }
  export default classes
}

declare module '*.css'
