#!/usr/bin/env node
/**
 * Generate a dsh web profile that uses only @dsh-selfuse workspace bundles.
 *
 * The generated profile deliberately has no out-of-tree dependencies: every
 * bundle is resolved from the dsh installation (the source monorepo) before
 * the profile directory. This works because the selfuse packages are added to
 * apps/cli and healProfilesModuleFallback links their closure into
 * $DSH_HOME/profiles/node_modules.
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { createRequire } from 'node:module'
import yaml from 'js-yaml'

const require = createRequire(import.meta.url)
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

function fileURLToPath(url) {
  return url.replace(/^file:\/\//, '')
}

const args = process.argv.slice(2)
function argValue(name, fallback) {
  const idx = args.indexOf(`--${name}`)
  return idx >= 0 && args[idx + 1] ? args[idx + 1] : fallback
}
const dryRun = args.includes('--dry-run')
const dshHome = argValue('dsh-home', process.env.DSH_HOME || join(homedir(), '.dsh'))
const manifestPath = argValue('manifest', join(repoRoot, 'config/selfuse/profiles.build.yml'))

if (!existsSync(manifestPath)) {
  console.error(`profile manifest not found: ${manifestPath}`)
  process.exit(1)
}

const manifest = yaml.load(readFileSync(manifestPath, 'utf8'))
const name = manifest.name || 'web'
const bundleList = manifest.bundles || []
const patchPlugins = manifest.patchPlugins || []
const profileDir = join(dshHome, 'profiles', name)

function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) return false
  if (!dryRun) writeFileSync(path, content)
  return true
}

const packageJson = {
  name: `dsh-profile-${name}`,
  private: true,
  dependencies: {},
  dsh: {
    profile: {
      bundles: bundleList,
    },
  },
}

const patchLines = [
  '# Generated by scripts/selfuse/generate-profile.mjs — do not edit by hand.',
  '# Patch-mounted ordinary plugins (not bundles).',
  ...patchPlugins.map((pkg) => {
    const last = pkg.split('/').pop()
    const id = last.startsWith('dsh-') ? last : `dsh-${last}`
    return `- insert:\n    - id: ${id}\n      name: '${pkg}'`
  }),
  '',
]
const patchContent = patchLines.join('\n')

const workspaceContent = `# Generated by scripts/selfuse/generate-profile.mjs — do not edit by hand.
packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
`

console.log(`Selfuse profile generator`)
console.log(`  repo root: ${repoRoot}`)
console.log(`  manifest:  ${manifestPath}`)
console.log(`  profile:   ${profileDir}`)
console.log(`  bundles:   ${bundleList.length}`)
console.log(`  patches:   ${patchPlugins.length}`)

if (dryRun) {
  console.log('\n[dry-run] would write:')
  console.log(`  ${join(profileDir, 'package.json')}`)
  console.log(`  ${join(profileDir, 'cordis.patch.yml')}`)
  console.log(`  ${join(profileDir, 'pnpm-workspace.yaml')}`)
  process.exit(0)
}

mkdirSync(profileDir, { recursive: true })
const changed = [
  writeIfChanged(join(profileDir, 'package.json'), JSON.stringify(packageJson, null, 2) + '\n'),
  writeIfChanged(join(profileDir, 'cordis.patch.yml'), patchContent),
  writeIfChanged(join(profileDir, 'pnpm-workspace.yaml'), workspaceContent),
]
console.log(`\n${changed.some(Boolean) ? 'Files written/updated' : 'Files already current'}.`)
for (const file of ['package.json', 'cordis.patch.yml', 'pnpm-workspace.yaml']) {
  console.log(`  - ${join(profileDir, file)}`)
}
