#!/usr/bin/env node
/**
 * Generate a dsh web profile that uses only @dsh-selfuse workspace bundles.
 *
 * Managed bundles resolve from the source monorepo; dependencies explicitly
 * installed with `dsh plugin` are retained in the profile so the native CLI
 * remains usable across regeneration.
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { createRequire } from 'node:module'
import yaml from 'js-yaml'

const require = createRequire(import.meta.url)
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..')

const args = process.argv.slice(2)
function argValue(name, fallback) {
  const idx = args.indexOf(`--${name}`)
  return idx >= 0 && args[idx + 1] ? args[idx + 1] : fallback
}
const dryRun = args.includes('--dry-run')
const dshHome = argValue('dsh-home', process.env.DSH_HOME || join(homedir(), '.dsh'))
const manifestPath = argValue('manifest', join(repoRoot, 'config/selfuse/profiles.build.yml'))

if (!existsSync(manifestPath)) {
  console.error(`profile manifest not found: ${manifestPath}`)
  process.exit(1)
}

const manifest = yaml.load(readFileSync(manifestPath, 'utf8'))
const name = manifest.name || 'web'
const bundleList = manifest.bundles || []
const patchPlugins = manifest.patchPlugins || []
const disabledRows = manifest.disabledRows || []
const rowConfigs = manifest.rowConfigs || {}
const profileDir = join(dshHome, 'profiles', name)
const packagePath = join(profileDir, 'package.json')
const patchPath = join(profileDir, 'cordis.patch.yml')
const localOverridesMarker = '# Local instance overrides (preserved by profile generator).'
const previousPatch = existsSync(patchPath) ? readFileSync(patchPath, 'utf8') : ''
const localOverridesAt = previousPatch.indexOf(localOverridesMarker)
const localOverrides = localOverridesAt < 0 ? '' : previousPatch.slice(localOverridesAt)
const existingPackage = existsSync(packagePath) ? JSON.parse(readFileSync(packagePath, 'utf8')) : {}
const existingDependencies = existingPackage.dependencies ?? {}
if (typeof existingDependencies !== 'object' || Array.isArray(existingDependencies)) {
  throw new Error(`profile dependencies must be an object: ${packagePath}`)
}
const cliBundles = (existingPackage.dsh?.profile?.bundles ?? [])
  .filter(pkg => Object.hasOwn(existingDependencies, pkg) && !bundleList.includes(pkg))

function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) return false
  if (!dryRun) writeFileSync(path, content)
  return true
}

const packageJson = {
  name: `dsh-profile-${name}`,
  private: true,
  dependencies: existingDependencies,
  dsh: {
    profile: {
      bundles: [...bundleList, ...cliBundles],
    },
  },
}

const patchLines = [
  '# Generated by scripts/selfuse/generate-profile.mjs — do not edit by hand.',
  '# Managed row overrides inherited from bundle layers.',
  ...disabledRows.map(id => `- id: ${id}\n  disabled: true`),
  ...Object.entries(rowConfigs).map(([id, config]) => yaml.dump(
    [{ id, config }],
    { lineWidth: -1, noRefs: true },
  ).trimEnd()),
  '',
  '# Patch-mounted ordinary plugins (not bundles).',
  ...patchPlugins.map((pkg) => {
    const last = pkg.split('/').pop()
    const id = last.startsWith('dsh-') ? last : `dsh-${last}`
    return `- insert:\n    - id: ${id}\n      name: '${pkg}'`
  }),
  '',
]
const patchContent = patchLines.join('\n') + (localOverrides ? `\n${localOverrides}` : '')

const workspaceContent = `# Generated by scripts/selfuse/generate-profile.mjs — do not edit by hand.
packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
`

console.log(`Selfuse profile generator`)
console.log(`  repo root: ${repoRoot}`)
console.log(`  manifest:  ${manifestPath}`)
console.log(`  profile:   ${profileDir}`)
console.log(`  bundles:   ${bundleList.length}`)
console.log(`  patches:   ${patchPlugins.length}`)
console.log(`  disabled:  ${disabledRows.length}`)
console.log(`  configured:${Object.keys(rowConfigs).length}`)

if (dryRun) {
  console.log('\n[dry-run] would write:')
  console.log(`  ${join(profileDir, 'package.json')}`)
  console.log(`  ${join(profileDir, 'cordis.patch.yml')}`)
  console.log(`  ${join(profileDir, 'pnpm-workspace.yaml')}`)
  process.exit(0)
}

mkdirSync(profileDir, { recursive: true })
const changed = [
  writeIfChanged(packagePath, JSON.stringify(packageJson, null, 2) + '\n'),
  writeIfChanged(patchPath, patchContent),
  writeIfChanged(join(profileDir, 'pnpm-workspace.yaml'), workspaceContent),
]
console.log(`\n${changed.some(Boolean) ? 'Files written/updated' : 'Files already current'}.`)
for (const file of ['package.json', 'cordis.patch.yml', 'pnpm-workspace.yaml']) {
  console.log(`  - ${join(profileDir, file)}`)
}
